spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/holdinghands
    username: caio
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
  flyway:
    locations: classpath:db/migration
